#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)
require 'george/cli'

Signal.trap('INT') do
  warn('interrupted')
  exit(1)
end

begin
  George::CLI.start
rescue George::CLI::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
