#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require 'michael/cli'
require 'tty-prompt'

Signal.trap('INT') do
  warn('interrupted')
  exit(1)
end

begin
  Michael::CLI.start
rescue TTY::Reader::InputInterrupt
  warn('interrupted')
  exit(1)
rescue Michael::Error => e
  puts "Error: #{e.message}"
  exit 1
end
